Feature/lab1 create web site
DmitrySychevDev/marvel pull request #1
Opened 2022-11-02 05:55 UTC by DmitrySychevDev

2022-11-02 06:53 UTC, konstantinzelinsky commented
Привет! Переименуй, пожалуйста, PR в соответствии с примером, который указан в notion для того, чтобы получить доп баллы за это.
В первой лабораторной напоминаю об этом, в дальнейшем доп баллы ставить не буду.
Сообщения в коммитах тоже должны быть более короткими

2022-11-02 11:59 UTC, konstantinzelinsky commented
Нейминг опять неправильный

2022-11-02 12:14 UTC, DmitrySychevDev commented
Снова поменял название

2022-11-02 17:34 UTC, annamyamikova commented
У меня не запускается даже из-за CORs ошибки. Скорее из-за шрифтов не дает.
Используй такой импорт
@import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;700;800;900&display=swap');

2022-11-03 04:06 UTC, DmitrySychevDev commented
Переместил импорт шрифтов в css

2022-11-03 14:44 UTC, konstantinzelinsky requested changes
Не проходит валидацию

2022-11-03 14:45 UTC, konstantinzelinsky commented
Документ не проходит валидацию, проблемы с alt для картинок.

Желтая картинка, которая в бэкграунде обрезается
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/57330800/199752614-18c111f5-f824-4cc4-b56e-907bed27f3d0.png">

В футере волна обрезана
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/57330800/199752738-f0077095-2073-4230-9b20-a4d68de8b90c.png">

2022-11-04 15:13 UTC, DmitrySychevDev commented
Исправил (я пытался исправить последний комит ,но что-то пошла не по плану)

2022-11-04 19:18 UTC, konstantinzelinsky commented
<img width="1409" alt="image" src="https://user-images.githubusercontent.com/57330800/200057727-9e5f30ae-5190-4dcd-8837-af445b109925.png">

Еще остались ошибки в валидаторе

2022-11-04 19:18 UTC, konstantinzelinsky requested changes
Еще остались ошибки в валидаторе

2022-11-05 04:34 UTC, DmitrySychevDev commented
Исправленно

2022-11-05 07:34 UTC, konstantinzelinsky commented
Принял, 14 баллов

2022-11-05 07:34 UTC, konstantinzelinsky approved these changes

2022-11-05 07:34 UTC, merged